In [1]:
!pip install -U sentence-transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 KB 909.4 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.8/5.8 MB 41.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 33.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 182.4/182.4 KB 6.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 58.5 MB/s eta 0:00:00
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125938 sha256=83359c2bcae93b9b74a697fc83e92c60c8f3ce0d5c8b4834003d2a5304c3c831
  Stored in directory: /root/.cache/pip/wheels/5e/6f/8c/d88aec621f3f542d26fac0342bef5e693335d125f4e54aeffe
Successfully built sentence-transformers


# Generate **embedding**

In [2]:
from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer('all-MiniLM-L6-v2')


Downloading:   0%|          | 0.00/1.18k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/190 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/612 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/116 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/39.3k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/466k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/350 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/13.2k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/349 [00:00<?, ?B/s]

In [4]:
sentences = ['This framework generates embedding for each input sentence', 'Sentences are passed as a list of String.']

embedding = model.encode(sentences) 

for sentence, embedding in zip(sentences, embedding):
  print("Sentence:", sentence)
  print("Embedding:", embedding)

  print("")

Sentence: This framework generates embedding for each input sentence
Embedding: [-6.91256858e-03 -3.62894610e-02 -2.18610074e-02  1.13818049e-02
  4.25385050e-02  1.24863908e-01  3.01178619e-02 -3.15150246e-02
  3.38303857e-02 -7.66847357e-02  1.20255454e-02 -4.15239818e-02
  4.81980033e-02  1.67390052e-02 -7.33146071e-02  8.39759037e-02
  2.76713981e-03  4.19141427e-02 -4.62020636e-02 -1.12434991e-01
 -2.36533843e-02  6.44106269e-02  4.85518649e-02 -4.90318984e-02
 -4.05254923e-02  4.44705524e-02 -4.74039949e-02  6.91372575e-03
  1.09921902e-01  9.62933619e-03  3.35711241e-02 -3.39446329e-02
  1.79634579e-02  7.73302242e-02  3.85686615e-03  1.92318559e-02
 -1.43055450e-02  2.38439720e-02 -4.99975383e-02 -1.53257726e-02
 -2.34336369e-02 -1.26113985e-02  2.45836545e-02  1.66354403e-02
  8.51943269e-02 -4.40953597e-02 -8.38720277e-02 -1.40059963e-02
 -1.63426846e-02  1.66166890e-02 -8.57066214e-02 -5.24259321e-02
 -1.22594982e-02  2.15967540e-02 -2.22520493e-02  1.60497706e-02
 -1.098969

## **Cosine-Similarity**


In [5]:
emb1 = model.encode("I am eating Apple")
emb2 = model.encode("I like fruits")
cos_sim = util.cos_sim(emb1, emb2)
print("Cosine-Similarity:", cos_sim)

Cosine-Similarity: tensor([[0.5398]])


## Cosine Similarity between all pairs

In [6]:
sentences = ['A man is eating food.', 
             'A man is eating a piece of bread',
             'A man is riding a horse',
             'A woman is playing violin',
             'Two men pushed carts through the woods.',
             'A man is riding a white horse on an enclosed ground',
             'A monkey is playing drums.',
             'Someone in a gorilla costume is playing a set of drums']


#Encode all sentences
embeddings = model.encode(sentences)

#Compute cosine similarity betweeen all pairs
cos_sim = util.cos_sim(embeddings, embeddings)
cos_sim

tensor([[ 1.0000,  0.7412,  0.2394, -0.0718, -0.0333,  0.1644,  0.0476,  0.0559],
        [ 0.7412,  1.0000,  0.1383, -0.0833, -0.0178,  0.1129,  0.0374,  0.0074],
        [ 0.2394,  0.1383,  1.0000, -0.0308,  0.0410,  0.7260,  0.0768,  0.1347],
        [-0.0718, -0.0833, -0.0308,  1.0000, -0.1594, -0.0560,  0.1968,  0.2439],
        [-0.0333, -0.0178,  0.0410, -0.1594,  1.0000,  0.0781, -0.0380, -0.0819],
        [ 0.1644,  0.1129,  0.7260, -0.0560,  0.0781,  1.0000,  0.0502,  0.1162],
        [ 0.0476,  0.0374,  0.0768,  0.1968, -0.0380,  0.0502,  1.0000,  0.6360],
        [ 0.0559,  0.0074,  0.1347,  0.2439, -0.0819,  0.1162,  0.6360,  1.0000]])

In [7]:
# Add all pairs to a list with their cosine similarity score

all_sentence_combinations = []

for i in range(len(cos_sim)-1):
  for j in range(i+1, len(cos_sim)):
    all_sentence_combinations.append((cos_sim[i][j], i, j))
all_sentence_combinations

[(tensor(0.7412), 0, 1),
 (tensor(0.2394), 0, 2),
 (tensor(-0.0718), 0, 3),
 (tensor(-0.0333), 0, 4),
 (tensor(0.1644), 0, 5),
 (tensor(0.0476), 0, 6),
 (tensor(0.0559), 0, 7),
 (tensor(0.1383), 1, 2),
 (tensor(-0.0833), 1, 3),
 (tensor(-0.0178), 1, 4),
 (tensor(0.1129), 1, 5),
 (tensor(0.0374), 1, 6),
 (tensor(0.0074), 1, 7),
 (tensor(-0.0308), 2, 3),
 (tensor(0.0410), 2, 4),
 (tensor(0.7260), 2, 5),
 (tensor(0.0768), 2, 6),
 (tensor(0.1347), 2, 7),
 (tensor(-0.1594), 3, 4),
 (tensor(-0.0560), 3, 5),
 (tensor(0.1968), 3, 6),
 (tensor(0.2439), 3, 7),
 (tensor(0.0781), 4, 5),
 (tensor(-0.0380), 4, 6),
 (tensor(-0.0819), 4, 7),
 (tensor(0.0502), 5, 6),
 (tensor(0.1162), 5, 7),
 (tensor(0.6360), 6, 7)]

In [8]:
#Sort list by the highest cosine similarity score
all_sentence_combinations = sorted(all_sentence_combinations, key=lambda x: x[0], reverse=True)

print("Top-5 most similar pairs:")
for score, i, j in all_sentence_combinations[0:5]:
    print("{} \t {} \t {:.4f}".format(sentences[i], sentences[j], cos_sim[i][j]))
     

Top-5 most similar pairs:
A man is eating food. 	 A man is eating a piece of bread 	 0.7412
A man is riding a horse 	 A man is riding a white horse on an enclosed ground 	 0.7260
A monkey is playing drums. 	 Someone in a gorilla costume is playing a set of drums 	 0.6360
A woman is playing violin 	 Someone in a gorilla costume is playing a set of drums 	 0.2439
A man is eating food. 	 A man is riding a horse 	 0.2394


# Semantic Search

In [9]:
from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer('clips/mfaq')

Downloading:   0%|          | 0.00/1.65k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/190 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/3.74k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/778 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/117 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/294 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/464 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/229 [00:00<?, ?B/s]

/usr/local/lib/python3.8/dist-packages/transformers/configuration_utils.py:369: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(


In [10]:
question = "How many models can I host on HuggingFace"
answer_1 = "All plans come with unlimited private models and datasets"
answer_2 = "AutoNLP is an automatic way to train and deploy state-of-the-art NLP models, seamlessly integrated with the Hugging Face ecosystem."
answer_3 = "Based on how much training data and model variants are created, we send you a compute cost and payment link - as low as $10 per job."

query_embedding = model.encode(question)
corpus_embeddings = model.encode([answer_1, answer_2, answer_3])

print(util.semantic_search(query_embedding, corpus_embeddings))

[[{'corpus_id': 0, 'score': 0.6575074791908264}, {'corpus_id': 2, 'score': 0.6102606654167175}, {'corpus_id': 1, 'score': 0.5705801248550415}]]


In [11]:
from transformers import pipeline

qa_model = pipeline("question-answering")
question = "Where do I live?"
context = "My name is Merve and I live in İstanbul."
qa_model(question = question, context = context)

No model was supplied, defaulted to distilbert-base-cased-distilled-squad and revision 626af31 (https://huggingface.co/distilbert-base-cased-distilled-squad).
Using a pipeline without specifying a model name and revision in production is not recommended.


Downloading:   0%|          | 0.00/473 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/261M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/213k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/436k [00:00<?, ?B/s]

{'score': 0.9538118243217468, 'start': 31, 'end': 39, 'answer': 'İstanbul'}

## Clustering

In [12]:
from sklearn.cluster import KMeans
import numpy as np

embedder = SentenceTransformer("all-MiniLM-L6-v2")

#corpus with example sentences
# Corpus with example sentences
corpus = ['A man is eating food.',
          'A man is eating a piece of bread.',
          'Horse is eating grass.',
          'A man is eating pasta.',
          'A Woman is eating Biryani.',
          'The girl is carrying a baby.',
          'The baby is carried by the woman',
          'A man is riding a horse.',
          'A man is riding a white horse on an enclosed ground.',
          'A monkey is playing drums.',
          'Someone in a gorilla costume is playing a set of drums.',
          'A cheetah is running behind its prey.',
          'A cheetah chases prey on across a field.',
          'The cheetah is chasing a man who is riding the horse.',
          'man and women with their baby are watching cheetah in zoo'
          ]
corpus_embeddings = embedder.encode(corpus)

# Normalize the embeddings to unit length
corpus_embeddings = corpus_embeddings /  np.linalg.norm(corpus_embeddings, axis=1, keepdims=True)

In [13]:
corpus_embeddings[0]

array([ 3.32415812e-02,  4.40610899e-03, -6.27700845e-03,  4.83787358e-02,
       -1.38702303e-01, -3.36174294e-02,  1.01128317e-01, -5.43849468e-02,
       -4.32477705e-02, -3.99410874e-02,  7.78634474e-03, -1.27489176e-02,
       -6.68302327e-02, -1.73865724e-02,  4.74505983e-02, -5.77242747e-02,
        1.01888388e-01, -9.11647337e-04,  8.22614953e-02, -5.03415577e-02,
        6.77303225e-02,  4.08765003e-02, -3.58018763e-02, -1.00682437e-01,
       -6.69353316e-03, -5.31686321e-02,  1.00335173e-01, -5.46136834e-02,
       -2.28481535e-02,  1.38387103e-02,  7.48658031e-02, -6.17880113e-02,
        6.39215931e-02,  1.62387453e-02, -5.32299578e-02, -3.86083946e-02,
        3.15275975e-02, -8.11530054e-02, -3.31432298e-02, -5.38525521e-04,
       -3.96068720e-03, -1.52733950e-02, -9.86412051e-04,  9.57987905e-02,
       -5.42920716e-02,  1.84571724e-02, -1.07143603e-01,  1.38885183e-02,
        3.94072160e-02, -2.69243363e-02, -9.15988907e-02, -1.14195561e-02,
        3.38136926e-02, -

In [16]:
clustering_model = KMeans(n_clusters=3)
clustering_model.fit(corpus_embeddings)
cluster_assignment = clustering_model.labels_
print(cluster_assignment)

[0 0 1 0 0 2 2 1 1 1 1 1 1 1 1]


In [17]:
clustered_sentences = {}
for sentence_id, cluster_id in enumerate(cluster_assignment):
  if cluster_id not in clustered_sentences:
    clustered_sentences[cluster_id] = []

  clustered_sentences[cluster_id].append(corpus[sentence_id])

clustered_sentences

{0: ['A man is eating food.',
  'A man is eating a piece of bread.',
  'A man is eating pasta.',
  'A Woman is eating Biryani.'],
 1: ['Horse is eating grass.',
  'A man is riding a horse.',
  'A man is riding a white horse on an enclosed ground.',
  'A monkey is playing drums.',
  'Someone in a gorilla costume is playing a set of drums.',
  'A cheetah is running behind its prey.',
  'A cheetah chases prey on across a field.',
  'The cheetah is chasing a man who is riding the horse.',
  'man and women with their baby are watching cheetah in zoo'],
 2: ['The girl is carrying a baby.', 'The baby is carried by the woman']}